### ISSUE TITLE
1.9.7.6wifi数据迁移崩溃，以及导出数据不包括下载列表

### ISSUE THREAD

**Issue by HenTaiCJN** [xiaojieonly/Ehviewer_CN_SXJ#1040]
wifi数据迁移时，空指针错误:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.alibaba.fastjson.JSONArray.toJavaList(java.lang.Class)' on a null object reference
	at com.hippo.ehviewer.client.data.GalleryInfo.galleryInfoFromJson(GalleryInfo.java:315)
	at com.hippo.ehviewer.dao.DownloadInfo.downloadInfoFromJson(DownloadInfo.java:251)
	at com.hippo.ehviewer.ui.wifi.WiFiClientActivity.lambda$dealWithDownloadInfo$4$com-hippo-ehviewer-ui-wifi-WiFiClientActivity(WiFiClientActivity.java:280)
	at com.hippo.ehviewer.ui.wifi.WiFiClientActivity$$ExternalSyntheticLambda4.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:1012)

换用本地db文件迁移时，下载列表似乎无法迁移

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版更新
