### ISSUE TITLE
缩略图和详情图加载失败，详情图显示网络异常

### ISSUE THREAD

**Issue by tianxiafeiyu** [xiaojieonly/Ehviewer_CN_SXJ#1218]
## 描述
eh版本：1.9.8.0
设备：小米平板3，安卓7
现象：缩略图和详情图加载失败，详情图显示网络异常；同一软件、同一网络环境、同一设置下，手机（安卓14）使用正常

## 日志
```
05-24 21:18:30.635  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
05-24 21:18:30.635  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
05-24 21:18:30.635  9136  9136 W System.err: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
05-24 21:18:30.635  9136  9136 W System.err: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
05-24 21:18:30.635  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:156)
05-24 21:18:30.635  9136  9136 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 21:18:30.635  9136  9136 W System.err: 	at org.conscrypt.Platform.checkTrusted(Platform.java:388)
05-24 21:18:30.635  9136  9136 W System.err: 	at org.conscrypt.Platform.checkServerTrusted(Platform.java:434)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1646)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:567)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1097)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1081)
05-24 21:18:30.636  9136  9136 W System.err: 	... 35 more
05-24 21:18:30.636  9136  9136 W System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-24 21:18:30.636  9136  9136 W System.err: 	... 51 more
05-24 21:18:30.636  9136  9136 W System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1136)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1091)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:878)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:749)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:714)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:833)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:706)
05-24 21:18:30.636  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:230)
05-24 21:18:30.637  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:209)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.Transmitter.newExchan e(Transmitter.java:169)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
05-24 21:18:30.637  9136  9136 W System.err: 	at okhttp3.RealCall.execute(RealCall.java:81)
05-24 21:18:30.637  9136  9136 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:273)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:154)
05-24 21:18:30.638  9136  9136 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-24 21:18:30.638  9136  9136 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-24 21:18:30.638  9136  9136 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-24 21:18:30.638  9136  9136 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-24 21:18:30.638  9136  9136 W System.err: 	at java.lang.Thread.run(Thread.java:760)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
05-24 21:18:30.638  9136  9136 W System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-24 21:18:30.638  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
05-24 21:18:30.638  9136  9136 W System.err: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
05-24 21:18:30.638  9136  9136 W System.err: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
05-24 21:18:30.638  9136  9136 W System.err: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
05-24 21:18:30.638  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:156)
05-24 21:18:30.638  9136  9136 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.Platform.checkTrusted(Platform.java:388)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.Platform.checkServerTrusted(Platform.java:434)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1646)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:567)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1097)
05-24 21:18:30.639  9136  9136 W System.err: 	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1081)
05-24 21:18:30.639  9136  9136 W System.err: 	... 35 more
05-24 21:18:30.639  9136  9136 W System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-24 21:18:30.639  9136  9136 W System.err: 	... 51 more
05-24 21:18:33.286  9136  9175 D IMGSRV  : gralloc_unregister_buffer:1708: ID=24493 ref=0
05-24 21:18:33.702  9136  9232 D EhEngine: https://exhentai.org/
05-24 21:18:33.713  9136  9232 D EhSSLSocketFactory: Host: exhentai.org Address: 178.175.128.252
```

**Comment by xiaojieonly** [comment]
手机系统问题，日志显示签名证书没找到，多半是系统不允许自建证书。。。
