### ISSUE TITLE
今天更新完出现了闪退的情况

### ISSUE THREAD

**Issue by SongyaCAT** [xiaojieonly/Ehviewer_CN_SXJ#1288]
下载和浏览的时候都出现了闪退，系统是安卓14的，以下是报错内容：
java.lang.RuntimeException: Can't create handler inside thread Thread[SpiderWorker-3,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.os.CountDownTimer$1.<init>(CountDownTimer.java:129)
	at android.os.CountDownTimer.<init>(CountDownTimer.java:129)
	at com.hippo.ehviewer.spider.SpiderQueen$TimeCount.<init>(SpiderQueen.java:1972)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.downloadImage(SpiderQueen.java:1425)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.runInternal(SpiderQueen.java:1693)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.run(SpiderQueen.java:1847)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)

**Comment by xiaojieonly** [comment]
1.9.8.4修了
