### ISSUE TITLE
NullPointerException with domain fronting on

### ISSUE THREAD

**Issue by aleck099** [xiaojieonly/Ehviewer_CN_SXJ#1314]
<details>
<summary>Logcat</summary>

```
java.lang.NullPointerException
	at java.net.Socket.nonNullAddress(Socket.java:431)
	at java.net.Socket.<init>(Socket.java:250)
	at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:956)
	at com.android.org.conscrypt.AbstractConscryptSocket.<init>(AbstractConscryptSocket.java:105)
	at com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:45)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:139)
	at com.android.org.conscrypt.Java8FileDescriptorSocket.<init>(Java8FileDescriptorSocket.java:47)
	at com.android.org.conscrypt.Platform.createFileDescriptorSocket(Platform.java:337)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:129)
	at com.hippo.network.EhSSLSocketFactory.createSocket(EhSSLSocketFactory.java:48)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:325)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:154)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
```
</details>

My debug：
![se1](https://github.com/user-attachments/assets/4f39fbec-b995-4c4c-8cb4-35e615d33079)
`address` can't be `null`

**Comment by xiaojieonly** [comment]
i don't know
