### ISSUE TITLE
归档下载导致闪退

### ISSUE THREAD

**Issue by fakepheonix** [xiaojieonly/Ehviewer_CN_SXJ#1405]
目前仅发现[https://exhentai.org/g/2248304/8a9794f86d/]()这个画廊出现闪退问题，且稳定复现，错误日志如下：
```
TIME=2024-09-03-15-12-49-231

======== PackageInfo ========
PackageName=com.xjs.ehviewer
VersionName=1.9.8.6
VersionCode=111
Signature=B4:F5:50:62:C8:34:6A:D4:09:9B:45:2C:22:69:2E:D5:E2:71:84:B3

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.MainActivity
TopScene=com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene

======== DeviceInfo ========
BOARD=YAL
BOOTLOADER=unknown
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HWYAL
DISPLAY=YAL-AL10 10.1.0.162(C00E160R8P12)
FINGERPRINT=HONOR/YAL-AL10/HWYAL:10/HUAWEIYAL-AL10/10.1.0.162C00:user/release-keys
HARDWARE=kirin980
HOST=cn-central-1b-9e6a65c311596523367901-2368177958-q4bjd
ID=HUAWEIYAL-AL10
MANUFACTURER=HUAWEI
MODEL=YAL-AL10
PRODUCT=YAL-AL10
RADIO=21C20B379S000C000,21C20B379S000C000
SERIAL=unknown
TAGS=release-keys
TYPE=user
USER=test
CODENAME=REL
INCREMENTAL=10.1.0.162C00
RELEASE=10
SDK=29
MEMORY=29.1 MiB
MEMORY_NATIVE=114.2 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=7.4 GiB

======== CrashInfo ========
java.lang.IllegalArgumentException: Invalid file URI: file:///storage/emulated/0/Download//EhviewerArchiver/[Abe Nattsu] SEX de Wakaru Unmei no Hito ~ Karada no Aishou... Tameshite miru? ~ Ch. 1-6 [Chinese] [裸單騎漢化].zip
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
	at android.content.ContentResolver.insert(ContentResolver.java:1872)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1100)
	at com.hippo.ehviewer.ui.dialog.ArchiverDownloadDialog$DownloadArchiverListener.onSuccess(ArchiverDownloadDialog.java:217)
	at com.hippo.ehviewer.ui.dialog.ArchiverDownloadDialog$DownloadArchiverListener.onSuccess(ArchiverDownloadDialog.java:182)
	at com.hippo.ehviewer.client.EhClient$Task.onPostExecute(EhClient.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:797)
	at android.os.AsyncTask.access$900(AsyncTask.java:195)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:814)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8679)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已尝试修复，十月份更新会上
