### ISSUE TITLE
应用因空指针问题导致闪退

### ISSUE THREAD

**Issue by voyage9691** [xiaojieonly/Ehviewer_CN_SXJ#1437]
下载了前面里站空指针问题的版本发现还是闪退，系统信息如图，报错信息如下
![Screenshot_2024-10-05-17-03-57-791_com android settings](https://github.com/user-attachments/assets/3ee7647c-f697-492d-9d2e-efbcec7b2197)

java.lang.RuntimeException: Unable to create application com.hippo.ehviewer.EhApplication: java.lang.NullPointerException: Attempt to write to field 'java.lang.String com.hippo.ehviewer.client.EhConfig.imageSize' on a null object reference in method 'void com.hippo.ehviewer.Settings.putImageResolution(java.lang.String)'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7429)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2365)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to write to field 'java.lang.String com.hippo.ehviewer.client.EhConfig.imageSize' on a null object reference in method 'void com.hippo.ehviewer.Settings.putImageResolution(java.lang.String)'
	at com.hippo.ehviewer.Settings.putImageResolution(Settings.java:795)
	at com.hippo.ehviewer.Settings.getImageResolution(Settings.java:788)
	at com.hippo.ehviewer.Settings.loadEhConfig(Settings.java:88)
	at com.hippo.ehviewer.Settings.initialize(Settings.java:66)
	at com.hippo.ehviewer.EhApplication.onCreate(EhApplication.java:169)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1323)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7422)
	... 9 more

**Comment by voyage9691** [comment]
总之现在先退回上个版本了

**Comment by xiaojieonly** [comment]
已修，下一版上

**Comment by voyage9691** [comment]
辛苦了
