### ISSUE TITLE
1.9.9.1更新后，残缺图片加载时会闪退

### ISSUE THREAD

**Issue by xcfj** [xiaojieonly/Ehviewer_CN_SXJ#1543]
因为网络等原因没有下载完成的残缺图片，在加载时会导致应用崩溃
![00000335](https://github.com/user-attachments/assets/15656289-d040-4941-8cdf-ffa27e661d1e)
比如这种图片

崩溃日志如下
```
======== CrashInfo ========
android.graphics.ImageDecoder$DecodeException: Input was incomplete.
	at android.graphics.ImageDecoder.onPartialImage(ImageDecoder.java:2211)
	at android.graphics.ImageDecoder.nDecodeBitmap(Native Method)
	at android.graphics.ImageDecoder.decodeBitmapInternal(ImageDecoder.java:1799)
	at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1909)
	at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1865)
	at com.hippo.lib.image.Image.<init>(Image.kt:51)
	at com.hippo.lib.image.Image.<init>(Image.kt:39)
	at com.hippo.lib.image.Image$Companion.decode(Image.kt:181)
	at com.hippo.lib.image.Image.decode(Unknown Source:2)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderDecoder.run(SpiderQueen.java:1795)
	at java.lang.Thread.run(Thread.java:1012)
	at com.hippo.lib.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
``` 

测试了一下在下载过程中多次直接关闭应用，最后下载完成后再点开，预加载到残缺图片是即崩溃，稳定复现
以前这种残缺图片剩余部分会显示为灰色，长按后点刷新即可重新下载

**Comment by t3228464187** [comment]
部分画廊的8,9,10页面进入后闪退
[Uploading logcat-2024-11-05-01-47-41-364.txt…]()

**Comment by 739471428** [comment]
1.9.9.2也还是有这问题

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版更新
