### ISSUE TITLE
1.9.9.1侧滑页面闪退

### ISSUE THREAD

**Issue by lanthth** [xiaojieonly/Ehviewer_CN_SXJ#1548]
如题，左侧栏任意触发方式都会闪退

**Comment by SaarChaffee** [comment]
附上同操作后闪退的 log

```
TIME=2024-11-05-18-30-04-363

======== PackageInfo ========
PackageName=com.xjs.ehviewer
VersionName=1.9.9.1
VersionCode=111
Signature=B4:F5:50:62:C8:34:6A:D4:09:9B:45:2C:22:69:2E:D5:E2:71:84:B3

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.MainActivity
TopScene=com.hippo.ehviewer.ui.scene.gallery.list.GalleryListScene

======== DeviceInfo ========
BOARD=kalama
BOOTLOADER=unknown
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=PQ82A11
DISPLAY=MyOS14.5.28MR2_NX712J
FINGERPRINT=nubia/CN_PQ82A11/PQ82A11:14/UKQ1.230917.001/20240729.144945:user/release-keys
HARDWARE=qcom
HOST=scl-sh-baremetal-23
ID=UKQ1.230917.001
MANUFACTURER=nubia
MODEL=NX712J
PRODUCT=CN_PQ82A11
RADIO=MPSS.DE.3.0-02351-KAILUA_GEN_PACK-1.24317.39.40606.17
SERIAL=unknown
TAGS=release-keys
TYPE=user
USER=zte
CODENAME=REL
INCREMENTAL=20240729.144945
RELEASE=14
SDK=34
MEMORY=53.8 MiB
MEMORY_NATIVE=30.2 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=11.0 GiB

======== CrashInfo ========
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:726)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:121)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1556)
	at com.hippo.widget.AvatarImageView.createCircleImage(AvatarImageView.java:486)
	at com.hippo.widget.AvatarImageView.onDraw(AvatarImageView.java:144)
	at android.view.View.draw(View.java:24098)
	at android.view.View.updateDisplayListIfDirty(View.java:22905)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.updateDisplayListIfDirty(View.java:22896)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.updateDisplayListIfDirty(View.java:22896)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.updateDisplayListIfDirty(View.java:22896)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.draw(View.java:24101)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:22905)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at com.google.android.material.navigation.NavigationView.lambda$dispatchDraw$0$com-google-android-material-navigation-NavigationView(NavigationView.java:588)
	at com.google.android.material.navigation.NavigationView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.google.android.material.shape.ShapeableDelegate.maybeClip(ShapeableDelegate.java:160)
	at com.google.android.material.navigation.NavigationView.dispatchDraw(NavigationView.java:588)
	at android.view.View.draw(View.java:24101)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:119)
	at android.view.View.updateDisplayListIfDirty(View.java:22905)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.updateDisplayListIfDirty(View.java:22896)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.updateDisplayListIfDirty(View.java:22896)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.draw(View.java:24101)
	at com.hippo.ehviewer.widget.EhNavigationView.draw(EhNavigationView.java:59)
	at android.view.View.updateDisplayListIfDirty(View.java:22905)
	at android.view.View.draw(View.java:23769)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
	at com.hippo.drawerlayout.DrawerLayout.drawChild(DrawerLayout.java:1051)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
	at android.view.View.draw(View.java:24101)
	at android.view.View.updateDisplayListIfDirty(View.java:22905)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
	at android.view.View.updateDisplayListIfDirty(View.java:22861)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5526)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5226)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4380)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2937)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10738)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1447)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1456)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1059)
	at android.view.Choreographer.doFrame(Choreographer.java:987)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1430)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:352)
	at android.app.ActivityThread.main(ActivityThread.java:9227)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)


```

**Comment by lanthth** [comment]
> 附上同操作后闪退的 log
> 
> ```
> TIME=2024-11-05-18-30-04-363
> 
> ======== PackageInfo ========
> PackageName=com.xjs.ehviewer
> VersionName=1.9.9.1
> VersionCode=111
> Signature=B4:F5:50:62:C8:34:6A:D4:09:9B:45:2C:22:69:2E:D5:E2:71:84:B3
> 
> ======== Runtime ========
> TopActivity=com.hippo.ehviewer.ui.MainActivity
> TopScene=com.hippo.ehviewer.ui.scene.gallery.list.GalleryListScene
> 
> ======== DeviceInfo ========
> BOARD=kalama
> BOOTLOADER=unknown
> CPU_ABI=arm64-v8a
> CPU_ABI2=
> DEVICE=PQ82A11
> DISPLAY=MyOS14.5.28MR2_NX712J
> FINGERPRINT=nubia/CN_PQ82A11/PQ82A11:14/UKQ1.230917.001/20240729.144945:user/release-keys
> HARDWARE=qcom
> HOST=scl-sh-baremetal-23
> ID=UKQ1.230917.001
> MANUFACTURER=nubia
> MODEL=NX712J
> PRODUCT=CN_PQ82A11
> RADIO=MPSS.DE.3.0-02351-KAILUA_GEN_PACK-1.24317.39.40606.17
> SERIAL=unknown
> TAGS=release-keys
> TYPE=user
> USER=zte
> CODENAME=REL
> INCREMENTAL=20240729.144945
> RELEASE=14
> SDK=34
> MEMORY=53.8 MiB
> MEMORY_NATIVE=30.2 MiB
> MEMORY_MAX=512.0 MiB
> MEMORY_TOTAL=11.0 GiB
> 
> ======== CrashInfo ========
> java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
> 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:726)
> 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
> 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:121)
> 	at android.graphics.Canvas.drawBitmap(Canvas.java:1556)
> 	at com.hippo.widget.AvatarImageView.createCircleImage(AvatarImageView.java:486)
> 	at com.hippo.widget.AvatarImageView.onDraw(AvatarImageView.java:144)
> 	at android.view.View.draw(View.java:24098)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22905)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22896)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22896)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22896)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.draw(View.java:24101)
> 	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22905)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at com.google.android.material.navigation.NavigationView.lambda$dispatchDraw$0$com-google-android-material-navigation-NavigationView(NavigationView.java:588)
> 	at com.google.android.material.navigation.NavigationView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at com.google.android.material.shape.ShapeableDelegate.maybeClip(ShapeableDelegate.java:160)
> 	at com.google.android.material.navigation.NavigationView.dispatchDraw(NavigationView.java:588)
> 	at android.view.View.draw(View.java:24101)
> 	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:119)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22905)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22896)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22896)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.draw(View.java:24101)
> 	at com.hippo.ehviewer.widget.EhNavigationView.draw(EhNavigationView.java:59)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22905)
> 	at android.view.View.draw(View.java:23769)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4629)
> 	at com.hippo.drawerlayout.DrawerLayout.drawChild(DrawerLayout.java:1051)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4390)
> 	at android.view.View.draw(View.java:24101)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22905)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4613)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4586)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22861)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5526)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5226)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4380)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2937)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10738)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1447)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1456)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:1059)
> 	at android.view.Choreographer.doFrame(Choreographer.java:987)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1430)
> 	at android.os.Handler.handleCallback(Handler.java:958)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:238)
> 	at android.os.Looper.loop(Looper.java:352)
> 	at android.app.ActivityThread.main(ActivityThread.java:9227)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
> ```

1.9.9.2 已修复
