### ISSUE TITLE
作者大大非常抱歉打扰到您，但是闪退问题确实十分困扰我

### ISSUE THREAD

**Issue by wuyilong1201** [xiaojieonly/Ehviewer_CN_SXJ#1570]
目前版本1.9.9.2，打开下载里打开原画下载的画廊会导致闪退，希望作者大大可以在接下来的更新中修复此问题，给作者大大增加了工作负担表示十分抱歉

**Comment by 603185423** [comment]
同样遇到了打开已下载画廊闪退的问题（个别画廊会崩溃）


这里先贴个trace


```
java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.drawable.BitmapDrawable
	at com.hippo.lib.image.Image.texImage(Image.kt:167)
	at com.hippo.lib.glview.image.ImageWrapper.texImage(ImageWrapper.java:138)
	at com.hippo.lib.glview.image.ImageTexture$Tile.texImage(ImageTexture.java:555)
	at com.hippo.lib.glview.glrenderer.NativeTexture.uploadToCanvas(NativeTexture.java:56)
	at com.hippo.lib.glview.glrenderer.NativeTexture.updateContent(NativeTexture.java:66)
	at com.hippo.lib.glview.image.ImageTexture.uploadNextTile(ImageTexture.java:278)
	at com.hippo.lib.glview.image.ImageTexture.-$$Nest$muploadNextTile(Unknown Source:0)
	at com.hippo.lib.glview.image.ImageTexture$Uploader.onGLIdle(ImageTexture.java:481)
	at com.hippo.lib.glview.view.GLRootView$IdleRunner.run(GLRootView.java:599)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

重置会崩溃的画廊的阅读进度可以单次避免闪退，但是第二次打开的时候依旧崩溃

这边贴个我这里会崩溃的画廊


https://exhentai.org/g/3089682/559b7599fe/


不确定是否每个环境都会崩


MIUI14/Android13，1.9.9.2和1.9.9.3均会在相同画廊崩溃

**Comment by wuyilong1201** [comment]
上边有个伙计，是用eh看第三方的压缩包也会闪退，猜测是只要e打开比较大的文件或者原图就会闪退，不知道是啥问题

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版更新
