### ISSUE TITLE
1.9.1.2下载闪退（附MIUI提示的log）

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#317]
更新后点击下载APP闪退，安卓12
MIUI报错如下![Screenshot_2022-07-31-22-24-08-743_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/48684035/182030952-63235fde-8459-4b40-a8e1-26082c0bffc9.jpg)

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
能将内容复制出来吗？

**Comment by Steve-337** [comment]
> 能将内容复制出来吗？

截图中的log？
java.lang.RuntimeException: Unable to start service com.hippo.ehviewer.download.DownloadService@8cdf53f with Intent { act=start cmp=com.xjs.ehviewer/com.hippo.ehviewer.download.DownloadService (has extras) }: java.lang.IllegalArgumentException: com.xjs.ehviewer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4816)
	at android.app.ActivityThread.access$2100(ActivityThread.java:276)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2169)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.IllegalArgumentException: com.xjs.ehviewer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
	at android.app.PendingIntent.getService(PendingIntent.java:686)
	at com.hippo.ehviewer.download.DownloadService.ensureDownloadingBuilder(DownloadService.java:216)
	at com.hippo.ehviewer.download.DownloadService.onStart(DownloadService.java:297)
	at com.hippo.ehviewer.download.DownloadManager.ensureDownload(DownloadManager.java:228)
	at com.hippo.ehviewer.download.DownloadManager.startDownload(DownloadManager.java:264)
	at com.hippo.ehviewer.download.DownloadService.handleIntent(DownloadService.java:156)
	at com.hippo.ehviewer.download.DownloadService.onStartCommand(DownloadService.java:142)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4798)
	... 9 more

**Comment by xiaojieonly** [comment]
已修复

**Comment by xiaojieonly** [comment]
> 

谢谢，这日志帮了大忙

**Comment by Steve-337** [comment]
> > 
> 
> 谢谢，这日志帮了大忙

应该的，毕竟“在没有错误日志的情況下诊断任何问题无异于闭眼开车”，作为普通用户能做的就是协助开发者查找问题
