### ISSUE TITLE
1.9.1.4版本启动闪退，报错 java.lang.SecurityException

### ISSUE THREAD

**Issue by BoomingBones** [xiaojieonly/Ehviewer_CN_SXJ#343]
机型华为荣耀8 JSN-AL00，系统Android版本 10
更新到1.9.1.4版本后出现启动闪退的问题，更新前版本是1.9.1.1之前的版本（具体是哪个不确定），闪退时Logcat报错如下：
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gms.persistent, PID: 13765
    java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10230 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7218)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10230 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
        at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
        at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
        at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
```

**Comment by xiaojieonly** [comment]
先退回旧版吧

**Comment by xiaojieonly** [comment]
华为手机。。。。

**Comment by BoomingBones** [comment]
找到问题了，是华为手机不兼容谷歌框架导致的。。之前给手机刷了个框架上去，删了就好了
