### ISSUE TITLE
1.9.4.5 什么都显示不出来

### ISSUE THREAD

**Issue by H-XZ** [xiaojieonly/Ehviewer_CN_SXJ#511]
什么都显示不出来，和断网的唯一区别是小机器人下面没有网络错误，收藏夹都是0
可以正常退出重登，但WiFi、流量、是否连VPN，都一样什么都不显示

**Comment by H-XZ** [comment]
补充，卸载重装后恢复正常，但还是不知道之前是什么原因

**Comment by status102** [comment]
同，放一部分log，APP似乎没法直接上传文件
```
02-07 23:03:55.957 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:03:55.957 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:03:55.957 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:03:55.957 27885 30481 I System.out: [OkHttp] sendRequest>>
02-07 23:03:55.957 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:03:55.967 27885 30282 D AppScoutStateMachine: 27885-ScoutStateMachinecreated
02-07 23:03:55.976 27885 27885 I BufferQueueConsumer: [](id:6ced0000000f,api:0,p:-1,c:27885) connect: controlledByApp=false
02-07 23:03:55.976 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#15] constructor()
02-07 23:03:55.977 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#15(BLAST Consumer)15](id:6ced0000000f,api:1,p:27885,c:27885) connect: api=1 producerControlledByApp=true
02-07 23:03:56.005 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus true
02-07 23:03:56.869 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus false
02-07 23:03:57.327 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#15(BLAST Consumer)15](id:6ced0000000f,api:1,p:27885,c:27885) disconnect: api 1
02-07 23:03:57.329 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#15] destructor()
02-07 23:03:57.330 27885 27885 I BufferQueueConsumer: [ViewRootImpl[SettingsActivity]#15(BLAST Consumer)15](id:6ced0000000f,api:0,p:-1,c:27885) disconnect
02-07 23:03:57.361 27885 30282 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:119765163049021 framenumber:16 blastBufferQueue is dead
02-07 23:03:58.964 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:03:58.964 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:03:58.964 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:04:00.748 27885 30481 I System.out: [com.mediatek.cta.CtaAdapter]:check permission begin!
02-07 23:04:05.803 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:04:52.102 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:04:52.102 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:04:52.102 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:04:52.102 27885 30481 I System.out: [OkHttp] sendRequest>>
02-07 23:04:52.102 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:04:52.110 27885 30282 D AppScoutStateMachine: 27885-ScoutStateMachinecreated
02-07 23:04:52.120 27885 27885 I BufferQueueConsumer: [](id:6ced00000010,api:0,p:-1,c:27885) connect: controlledByApp=false
02-07 23:04:52.120 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#16] constructor()
02-07 23:04:52.121 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#16(BLAST Consumer)16](id:6ced00000010,api:1,p:27885,c:27885) connect: api=1 producerControlledByApp=true
02-07 23:04:52.159 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus true
02-07 23:04:53.215 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus false
02-07 23:04:53.707 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#16(BLAST Consumer)16](id:6ced00000010,api:1,p:27885,c:27885) disconnect: api 1
02-07 23:04:53.709 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#16] destructor()
02-07 23:04:53.709 27885 27885 I BufferQueueConsumer: [ViewRootImpl[SettingsActivity]#16(BLAST Consumer)16](id:6ced00000010,api:0,p:-1,c:27885) disconnect
02-07 23:04:53.725 27885 30282 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:119765163049026 framenumber:16 blastBufferQueue is dead
02-07 23:04:55.115 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:04:55.115 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:04:55.115 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:04:55.117 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:05:23.572 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:05:23.572 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:05:23.572 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:05:23.572 27885 30481 I System.out: [OkHttp] sendRequest>>
02-07 23:05:23.572 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:05:23.582 27885 27885 I BufferQueueConsumer: [](id:6ced00000011,api:0,p:-1,c:27885) connect: controlledByApp=false
02-07 23:05:23.583 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#17] constructor()
02-07 23:05:23.584 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#17(BLAST Consumer)17](id:6ced00000011,api:1,p:27885,c:27885) connect: api=1 producerControlledByApp=true
02-07 23:05:23.588 27885 27936 D AppScoutStateMachine: 27885-ScoutStateMachinecreated
02-07 23:05:23.596 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus true
02-07 23:05:26.586 27885 30481 I System.out: [okhttp]:check permission begin!
02-07 23:05:26.586 27885 30481 I System.out: [okhttp]:not MMS!
02-07 23:05:26.586 27885 30481 I System.out: [okhttp]:not Email!
02-07 23:05:26.588 27885 30481 I System.out: [OkHttp] sendRequest<<
02-07 23:05:26.691 27885 27885 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1086698590, downTime=1086698590, deviceId=-1, source=0x101, displayId=0 }
02-07 23:05:26.692 27885 27885 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1086698594, downTime=1086698590, deviceId=-1, source=0x101, displayId=0 }
02-07 23:05:27.308 27885 27885 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1086699209, downTime=1086699209, deviceId=-1, source=0x101, displayId=0 }
02-07 23:05:27.351 27885 27885 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1086699252, downTime=1086699209, deviceId=-1, source=0x101, displayId=0 }
02-07 23:05:27.405 27885 27885 I BufferQueueConsumer: [](id:6ced00000012,api:0,p:-1,c:27885) connect: controlledByApp=false
02-07 23:05:27.406 27885 27885 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#18] constructor()
02-07 23:05:27.406 27885 27908 I BufferQueueProducer: [ViewRootImpl[MainActivity]#18(BLAST Consumer)18](id:6ced00000012,api:1,p:27885,c:27885) connect: api=1 producerControlledByApp=true
02-07 23:05:27.415 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus false
02-07 23:05:27.434 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus true
02-07 23:05:27.941 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#17(BLAST Consumer)17](id:6ced00000011,api:1,p:27885,c:27885) disconnect: api 1
02-07 23:05:27.945 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#17] destructor()
02-07 23:05:27.945 27885 27885 I BufferQueueConsumer: [ViewRootImpl[SettingsActivity]#17(BLAST Consumer)17](id:6ced00000011,api:0,p:-1,c:27885) disconnect
02-07 23:05:27.949 27885 27885 D View    : [Warning] assignParent to null: this = DecorView@ed0e98b[SettingsActivity]
02-07 23:05:27.961 27885 30282 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:119765163049029 framenumber:52 blastBufferQueue is dead
02-07 23:05:29.233 27885 27906 D EhEngine: https://exhentai.org/
02-07 23:05:29.240 27885 27906 I System.out: [com.mediatek.cta.CtaAdapter]:check permission begin!
02-07 23:05:29.244 27885 27906 D EhSSLSocketFactory: Host: exhentai.org Address: 178.175.128.252
02-07 23:05:29.245 27885 27906 I System.out: [com.mediatek.cta.CtaAdapter]:check permission begin!
02-07 23:05:31.247 27885 27906 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.tagName()' on a null object reference
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.parser.GalleryListParser.parse(GalleryListParser.java:198)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:274)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:150)
02-07 23:05:31.248 27885 27906 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.lang.Thread.run(Thread.java:920)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
02-07 23:05:31.248 27885 27906 W System.err: com.hippo.ehviewer.client.exception.EhException: 
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:150)
02-07 23:05:31.248 27885 27906 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-07 23:05:31.248 27885 27906 W System.err: 	at java.lang.Thread.run(Thread.java:920)
02-07 23:05:31.248 27885 27906 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
02-07 23:05:31.249 27885 27885 W System.err: com.hippo.ehviewer.client.exception.EhException: 
02-07 23:05:31.249 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
02-07 23:05:31.249 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
02-07 23:05:31.249 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
02-07 23:05:31.249 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:150)
02-07 23:05:31.249 27885 27885 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-07 23:05:31.249 27885 27885 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-07 23:05:31.250 27885 27885 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-07 23:05:31.250 27885 27885 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-07 23:05:31.250 27885 27885 W System.err: 	at java.lang.Thread.run(Thread.java:920)
02-07 23:05:31.250 27885 27885 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
02-07 23:05:31.250 27885 27885 W System.err: com.hippo.ehviewer.client.exception.EhException: 
02-07 23:05:31.250 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
02-07 23:05:31.250 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
02-07 23:05:31.250 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
02-07 23:05:31.251 27885 27885 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:150)
02-07 23:05:31.251 27885 27885 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-07 23:05:31.251 27885 27885 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-07 23:05:31.251 27885 27885 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-07 23:05:31.251 27885 27885 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-07 23:05:31.251 27885 27885 W System.err: 	at java.lang.Thread.run(Thread.java:920)
02-07 23:05:31.251 27885 27885 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
02-07 23:05:33.233 27885 32153 D libMEOW : meow new tls: 0x736699e400
02-07 23:05:33.234 27885 32153 D libMEOW : applied 1 plugins for [com.xjs.ehviewer]:
02-07 23:05:33.234 27885 32153 D libMEOW :   plugin 1: [libMEOW_gift.so]:
02-07 23:05:33.234 27885 32153 D libMEOW : meow delete tls: 0x736699e400
02-07 23:05:33.234 27885 27914 D ViewContentFactory: initViewContentFetcherClass
02-07 23:05:33.234 27885 27914 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
02-07 23:05:33.234 27885 27914 D ViewContentFactory: createInterceptor took 0ms
02-07 23:05:33.234 27885 27885 D IS_CTS_MODE: false
02-07 23:05:33.234 27885 27885 D MULTI_WINDOW_SWITCH_ENABLED: false
02-07 23:05:33.235 27885 27885 D DecorView[]: getWindowModeFromSystem  windowmode is 1
02-07 23:05:33.244 27885 27885 D ViewRootImpl[SettingsActivity]: hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
02-07 23:05:33.249 27885 27908 D OpenGLRenderer: Set useBufferAge=0, enablePartialUpdates=0
02-07 23:05:33.257 27885 27885 I BufferQueueConsumer: [](id:6ced00000013,api:0,p:-1,c:27885) connect: controlledByApp=false
02-07 23:05:33.257 27885 27885 I BLASTBufferQueue: [ViewRootImpl[SettingsActivity]#19] constructor()
02-07 23:05:33.258 27885 27908 I BufferQueueProducer: [ViewRootImpl[SettingsActivity]#19(BLAST Consumer)19](id:6ced00000013,api:1,p:27885,c:27885) connect: api=1 producerControlledByApp=true
02-07 23:05:33.277 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus false
02-07 23:05:33.300 27885 27885 D DecorView[]: onWindowFocusChanged hasWindowFocus true
02-07 23:05:33.791 27885 27908 I BufferQueueProducer: [ViewRootImpl[MainActivity]#18(BLAST Consumer)18](id:6ced00000012,api:1,p:27885,c:27885) disconnect: api 1
02-07 23:05:33.792 27885 27908 D OpenGLRenderer: endAllActiveAnimators on 0x7347604400 (NavigationMenuItemView) with handle 0x7347721800
02-07 23:05:33.792 27885 27908 D OpenGLRenderer: endAllActiveAnimators on 0x736690f200 (NavigationMenuItemView) with handle 0x7364a41be0
02-07 23:05:33.794 27885 27885 I BLASTBufferQueue: [ViewRootImpl[MainActivity]#18] destructor()
02-07 23:05:33.794 27885 27885 I BufferQueueConsumer: [ViewRootImpl[MainActivity]#18(BLAST Consumer)18](id:6ced00000012,api:0,p:-1,c:27885) disconnect
02-07 23:05:33.827 27885 27959 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:119765163049032 framenumber:204 blastBufferQueue is dead
```

**Comment by xiaojieonly** [comment]
> ViewContentFetcher

这个不是上传文件的日志，唯一用到上传文件的功能是图片搜索，这个日志是上报错误信息和获取画廊列表内容的日志，通常是因为网络不稳定导致的
