### ISSUE TITLE
进入“查看更多预览”页面，使用翻页功能跳转至后面页数，点击缩略图打开大图会发生应用闪退的问题，好像是图片越多越容易出现这种情况，大概是从更新了最新版后才发生

### ISSUE THREAD

**Issue by hdjsheifnjs** [xiaojieonly/Ehviewer_CN_SXJ#604]

**Comment by tiboogi** [comment]
同上，也有閃退問題

**Comment by houseyqh** [comment]
准确来说是通过缩略图跳到40之后的页数必定闪退

**Comment by xiaojieonly** [comment]
正在研究，我小米屌丝机目前跳转没啥问题。。。

**Comment by houseyqh** [comment]
> 

我这边同MIUI，k60p，缩略图点40后闪退这个问题现在是概率复现，有些画廊完全正常，有些就闪退

**Comment by yoyokirby** [comment]
我这边也有更多预览-打开大图-闪退的问题。一并发在这里了，条件有点不一样，我不用翻页，第一页也能闪退。机型为华为(手机平板均能稳定触发)。
经我测试条件如下: 
0.对于页数超过一定值的画廊(我这里似乎是页数大于100)
1.网站设置预览图行数大于4(需要捐赠才能选)
2.进入画廊，进入更多预览
3.点击任意页之大图(第一页也可以)
即可100%触发闪退。
当预览图行数是最低的4行(即一次加载20张预览)时，不会触发此闪退。

**Comment by italycalibur2019** [comment]
> 我这边也有更多预览-打开大图-闪退的问题。一并发在这里了，条件有点不一样，我不用翻页，第一页也能闪退。机型为华为(手机平板均能稳定触发)。 经我测试条件如下: 0.对于页数超过一定值的画廊(我这里似乎是页数大于100) 1.网站设置预览图行数大于4(需要捐赠才能选) 2.进入画廊，进入更多预览 3.点击任意页之大图(第一页也可以) 即可100%触发闪退。 当预览图行数是最低的4行(即一次加载20张预览)时，不会触发此闪退。

貌似不是所有的100张以上图片画廊都会闪退，好像是某些特定的画廊会百分百闪退

**Comment by yoyokirby** [comment]
> 我这边也有更多预览-打开大图-闪退的问题。一并发在这里了，条件有点不一样，我不用翻页，第一页也能闪退。机型为华为(手机平板均能稳定触发)。 经我测试条件如下: 0.对于页数超过一定值的画廊(我这里似乎是页数大于100) 1.网站设置预览图行数大于4(需要捐赠才能选) 2.进入画廊，进入更多预览 3.点击任意页之大图(第一页也可以) 即可100%触发闪退。 当预览图行数是最低的4行(即一次加载20张预览)时，不会触发此闪退。

1.9.5.3版本下我仍然能够稳定触发此闪退。

**Comment by italycalibur2019** [comment]
这是我闪退时保存的崩溃日志所报的错：
======== CrashInfo ========
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 649096 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:102)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.os.TransactionTooLargeException: data parcel size 649096 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:643)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	... 9 more
android.os.TransactionTooLargeException: data parcel size 649096 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:643)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
机型为Redmi Note 11T Pro，系统为MIUI 14.0.3，Eh版本为最新版。

**Comment by yoyokirby** [comment]
> 

才想起来可以有报告，这是我的错误报告
[logcat-2023-07-04-08-34-06-971.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/11943250/logcat-2023-07-04-08-34-06-971.txt)

**Comment by xiaojieonly** [comment]
已检查出可能存在问题的代码，近两天会更新一波

**Comment by houseyqh** [comment]
更新最新版后仍然未解决闪退问题，机型redmi k60pro，系统miui 14.0.23，错误日志如下
TIME=2023-07-15-02-23-27-128

======== PackageInfo ========
PackageName=com.xjs.ehviewer
VersionName=1.9.5.4
VersionCode=111
Signature=B4:F5:50:62:C8:34:6A:D4:09:9B:45:2C:22:69:2E:D5:E2:71:84:B3

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.GalleryActivity
TopScene=null

======== DeviceInfo ========
BOARD=kalama
BOOTLOADER=unknown
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=socrates
DISPLAY=TKQ1.220905.001 test-keys
FINGERPRINT=Redmi/socrates/socrates:13/TKQ1.220905.001/V14.0.23.0.TMKCNXM:user/release-keys
HARDWARE=qcom
HOST=pangu-build-component-system-68918-0tv76-kfwj9-92xt9
ID=TKQ1.220905.001
MANUFACTURER=Xiaomi
MODEL=22127RK46C
PRODUCT=socrates
RADIO=MPSS.DE.3.0-Mar 27 2023-13:01:15,MPSS.DE.3.0-Mar 27 2023-13:01:15
SERIAL=unknown
TAGS=release-keys
TYPE=user
USER=builder
CODENAME=REL
INCREMENTAL=V14.0.23.0.TMKCNXM
RELEASE=13
SDK=33
MEMORY=28.0 MiB
MEMORY_NATIVE=74.6 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=10.9 GiB

======== CrashInfo ========
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 637808 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:102)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.os.TransactionTooLargeException: data parcel size 637808 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:643)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	... 9 more
android.os.TransactionTooLargeException: data parcel size 637808 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:643)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by houseyqh** [comment]
这边再给一个能够稳定触发闪退bug的画廊
https://exhentai.org/g/2608387/1218594a98/

**Comment by yoyokirby** [comment]
1.9.5.4我依然能够触发闪退
覆盖安装1.9.5.1后闪退
再覆盖安装1.9.5.0后不再闪退(测试了几个几百页画廊)

**Comment by houseyqh** [comment]
> 

感谢老哥，覆盖安装1.9.5.0后已经恢复正常

**Comment by UNSCs117** [comment]
唔我更新1.9.5.4后也还会触发闪退bug，而且条件还是和原本一直，图超过200的画廊(阈值不明但大部分都是过200的)，从画廊只显示前20张图的预览界面点开图再翻页就没事，但是一旦进入20张图下的“查看更多预览”后点开任意一张图都会闪退(甚至点开第1张图，而且明显看出图片已经加载完毕也会闪退)。不过如楼上所说覆盖安装1.9.5.0后原版本怎么开都闪退的画廊就不再闪退了。但是再次更新至1.9.5.4则还是会在同一画廊以同样的方式产生闪退bug。。。

**Comment by UNSCs117** [comment]
目前拿手上仅有的3个手机(小米note10pro,安卓13；mipad5，安卓13；荣耀note10，安卓8.1，三个均更新至1.9.5.4)测试后确定应该是固定画廊会产生崩溃(代表是画廊https://exhentai.org/g/2594652/81d7bff926/，三花栗鼠屋Patreon/Fanbox part5)，3个手机在显示20张图的预览界面点开图没问题，但一点击“查看更多预览”后点击任意图都会导致闪退，覆盖安装1.9.5.0就没问题了，但是更新至1.9.5.1及以上就会在同一画廊出现同一bug。

**Comment by italycalibur2019** [comment]
这里再提供一个新版本稳定闪退的画廊：https://exhentai.org/g/1536430/993f86a710/
同样回滚到1.9.5.0不会闪退
手机型号：Redmi Note 11T Pro
系统版本号：MIUI 14.0.5

**Comment by UNSCs117** [comment]
可惜，目前的1.9.5.5仍然会有画廊闪退的问题。。。crash report中仍然是android.os.TransactionTooLargeException: data parcel size太大超过1MB的问题。根据cndc速成教学(?)：
**根据官方的建议就是减小传输的数据大小，或者拆分数据分次传输，但是如果数据量真的很大且需一次性传输有没解决方法呢，当然有

- 数据保存到static全局变量中
- 数据保存到本地存储中，比如本地文件或数据库，在目标Activity中再提取出来
- 通过EventBus.postSticky传递包含传递数据的粘性事件，在目标Activity中接收该事件提取数据**
出此问题还是回到1.9.5.0就可以解决，总之还是没修好bug。。。小杰加油啊！

**Comment by xiaojieonly** [comment]
> 可惜，目前的1.9.5.5仍然会有画廊闪退的问题。。。crash report中仍然是android.os.TransactionTooLargeException: data parcel size太大超过1MB的问题。根据cndc速成教学(?)： **根据官方的建议就是减小传输的数据大小，或者拆分数据分次传输，但是如果数据量真的很大且需一次性传输有没解决方法呢，当然有
> 
> * 数据保存到static全局变量中
> * 数据保存到本地存储中，比如本地文件或数据库，在目标Activity中再提取出来
> * 通过EventBus.postSticky传递包含传递数据的粘性事件，在目标Activity中接收该事件提取数据**
>   出此问题还是回到1.9.5.0就可以解决，总之还是没修好bug。。。小杰加油啊！

现在的问题是我不知道数据源头在哪。。。
你们提供的日志信息没有一行是指向app的代码的😵‍💫😵‍💫😵‍💫😵‍💫

**Comment by xiaojieonly** [comment]
不过我又修了一下，你们到时候看看1.9.5.6

**Comment by UNSCs117** [comment]
> 不过我又修了一下，你们到时候看看1.9.5.6

可惜的是还是同样的闪退问题。。。我上传一下1.9.5.6的logcat和crash吧
[crash-2023-07-29-10-20-50-772.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12206735/crash-2023-07-29-10-20-50-772.log)
[logcat-2023-07-29-10-21-14-329.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12206736/logcat-2023-07-29-10-21-14-329.txt)
准确闪退发生时间是07/29 10:20:50，对着手机时间确定的，毫秒就不知道了，logcat是在闪退1min后生成的。
不知道有没有帮助。。。

**Comment by UNSCs117** [comment]
前2个是miui(安卓13)下的log，下面2个是华为(安卓8.1.0)下的log：
[crash-2023-07-29-11-15-59-539.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12206752/crash-2023-07-29-11-15-59-539.log)
[logcat-2023-07-29-11-18-45-075.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12206753/logcat-2023-07-29-11-18-45-075.txt)
闪退时间为07/29 11:15:59-11:16:01之间

**Comment by xiaojieonly** [comment]
我看一下

**Comment by xiaojieonly** [comment]
更新了 @UNSCs117 ,你看下1.9.5.7有问题没

**Comment by UNSCs117** [comment]
> 更新了 @UNSCs117 ,你看下1.9.5.7有问题没

不幸的是此bug仍然存在……我尝试卸载再重装1.9.5.7后也一样有，使用多个手机(小米+安卓13，华为+安卓8，模拟器安卓12)都实验过了(未导入之前备份的数据完全卸载重装也一样)。
鉴于华为的logcat数据和crash完全一样我就不上传了，但是小米的比较详细所以我就上传这些
[crash-2023-08-05-08-34-21-344.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12266460/crash-2023-08-05-08-34-21-344.log)
[logcat-2023-08-05-08-34-30-788.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12266461/logcat-2023-08-05-08-34-30-788.txt)

闪退发生在8月5日8:34:20至21秒左右，实验的是https://exhentai.org/g/2594652/81d7bff926/
之后其他手机也实验了https://exhentai.org/g/2032487/c332a9047b/和https://exhentai.org/g/2629983/e3a3008421/也一样触发闪退。

同一手机第2次触发闪退(时间9:34:47)：
[crash-2023-08-05-09-34-47-351.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12266483/crash-2023-08-05-09-34-47-351.log)
[logcat-2023-08-05-09-38-08-278.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12266484/logcat-2023-08-05-09-38-08-278.txt)
实验的是https://exhentai.org/g/2629983/e3a3008421/

不知道有没有用啊……

**Comment by xiaojieonly** [comment]
只有特定画廊会崩溃？

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/f637c662-e3fe-462d-ba0d-d5a767dd2195)
是不是你系统开启了黑夜模式导致的？

**Comment by xiaojieonly** [comment]
我看了你给的几个画廊，从预览页跳转到浏览页都是正常的，在我的手机上
![Screenshot_2023-08-05-21-09-52-948_com android se](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/959a1b02-9ced-405a-a5cc-7eb7e207e230)
@UNSCs117

**Comment by UNSCs117** [comment]
> ![image](https://user-images.githubusercontent.com/49278135/258586244-f637c662-e3fe-462d-ba0d-d5a767dd2195.png) 是不是你系统开启了黑夜模式导致的？

感谢，确实是这个问题。我手机开了深色模式，但是EH并未打开深色模式。EH内的主题使用黑色就会出现上述几个特定画廊闪退的bug，换到暗色/亮色就没问题了……

**Comment by UNSCs117** [comment]
虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了

**Comment by xiaojieonly** [comment]
终于破案了，操。。。。

**Comment by xiaojieonly** [comment]
> 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了

这绝对是纯纯的系统问题🤮🤮🤮

**Comment by UNSCs117** [comment]
> > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮

麻了，那个安卓13的小米手机改了主题颜色后就正常了，之后切换到黑暗也没关系了，但是其他俩设备还是这个问题，目前是完全找不到解决办法……一个是MiPad5，闪退后的crash报告一次都没生成，logcat里找了下发现和暗黑主题完全无关：
[logcat-2023-08-05-20-27-08-113.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12267913/logcat-2023-08-05-20-27-08-113.txt)(截取了闪退时段内的报告)


安卓8.0的华为虽然有crash报告，但是logcat里也和前面2个完全没有类似的地方：
[logcat-2023-08-05-20-21-27-074.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12267901/logcat-2023-08-05-20-21-27-074.txt)(同样截取了闪退时段内的报告)

这都什么事情啊，太离谱了，3台设备3个不同的原因产生了3个同样的闪退结果

**Comment by UNSCs117** [comment]
2台设备均卸载最新版后再重新安装了一次，MiPad5(最新版的系统)是勾选了“应用崩溃时保存错误日志”，但至今为止一个crash report都没有见到过，倒是有几次看到parse_error下面一堆文件，之后就不再生成了。

**Comment by yoyokirby** [comment]
看到更新，补充一下(我没有测试过新版)，我的使用环境是EHV固定设置纯黑主题，但EHV不跟随系统。系统23-7点自动换暗黑模式。

**Comment by qw853286543** [comment]
> > 虽然，不知道啥但是黑色主题会在1.9.5.0之后出现这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮
机型：红米note12 turbo，安卓13，关闭深色模式，依旧有这个闪退的问题，某个上千页的特定画廊，跳转到40页之后就会闪退
最新的1.9.5.9版

**Comment by hdjsheifnjs** [comment]
> > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮

最新版是好了些，但不知道为什么有些画廊还是有闪退问题有些画廊就没事，而且我手机也没开黑色主题

**Comment by hdjsheifnjs** [comment]
> > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮

更新了最新版后依旧有闪退问题，而且好像比上个版本更严重了些，本来能正常点开的又会闪退，好像是画廊数量越多越容易发生

**Comment by italycalibur2019** [comment]
> > > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> > 
> > 
> > 这绝对是纯纯的系统问题🤮🤮🤮
> 
> 更新了最新版后依旧有闪退问题，而且好像比上个版本更严重了些，本来能正常点开的又会闪退，好像是画廊数量越多越容易发生
我的机型问题依旧，并且看了看日志多了个这个信息：
======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.GalleryActivity
TopScene=null
好像是出现了空指针异常
日志报错还是这个：
======== CrashInfo ========
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 649340 bytes

**Comment by UNSCs117** [comment]
> > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
	at com.hippo.ehviewer.widget.LimitsCountView.onLoadData(LimitsCountView.java:146)
	at com.hippo.ehviewer.widget.LimitsCountView.onLoadData(LimitsCountView.java:142)
	at com.hippo.ehviewer.ui.MainActivity.onDrawerOpened(MainActivity.java:929)
	at com.hippo.drawerlayout.DrawerLayout.dispatchOnDrawerOpened(DrawerLayout.java:995)
	at com.hippo.drawerlayout.DrawerLayout.onAnimationEnd(DrawerLayout.java:707)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1384)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:904)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

上面这个闪退代码我是用小米的第三方应用闪退扒下来的。由于几天前E站更新了导致原本不会闪退的1.9.5.0出现看的这张图后面所有图都加载失败甚至下载也出这问题的神奇情况，不得已转到1.9.5.1及之后会闪退的新版。。。不知道您能不能优化一下(虽然这个话题关了)

**Comment by UNSCs117** [comment]
> > 虽然但是，不知道为啥就黑色主题会在1.9.5.0之后出这个bug……太神奇了
> 
> 这绝对是纯纯的系统问题🤮🤮🤮

前几天e站更新了导致不会闪退的最高版本1.9.5.0出现预览图的后面所有图都解析失败，包括下载也会这样，不得不换用1.9.5.1及以上会闪退的版本了。。。

**Comment by UNSCs117** [comment]
感谢，刚发布的1.9.6.7大概看了一下，我打开上面那个代表画廊查看更多预览再点开图片后确实不再闪退了，待我大概翻一下，不过应该是修复了，谢谢作者！
