### ISSUE TITLE
从更多预览进入阅读模式崩溃

### ISSUE THREAD

**Issue by xwjcool123** [xiaojieonly/Ehviewer_CN_SXJ#668]
版本：1.9.5.2
系统：MIUI 14.0.6

如何复现：
1. 点开任意画廊
2. 进入更多预览
3. 点击任意预览图进入阅览模式，应用崩溃

直接点击画廊也买你的预览时可以正常进入阅读的，只有从更多预览进入才会崩溃。

**Comment by lomemeng** [comment]
也是1.9.5.2版本，用的华为mate10也闪退，应该不是设备的原因，亲测在下载、翻页、设置、甚至小窗口切换时都闪退过。1.9.5.1没有这个问题，望修复

**Comment by xwjcool123** [comment]
补充：从更多预览切出再切回也会造成崩溃

**Comment by xwjcool123** [comment]
补充：从更多预览切出再切回也会造成崩溃

**Comment by kj415j45** [comment]
附参考日志

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 807120 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:102)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.os.TransactionTooLargeException: data parcel size 807120 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:646)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	... 9 more
android.os.TransactionTooLargeException: data parcel size 807120 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:646)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)


```

**Comment by xiaojieonly** [comment]
> 

从日志上看这个闪退是系统问题，和app关系不大，日志里没有一个类是app的。。。。
