### ISSUE TITLE
列表页解析出错

### ISSUE THREAD

**Issue by Gaojianli** [xiaojieonly/Ehviewer_CN_SXJ#794]
Eh可以正常解析，但是Ex解析失败
```
10-19 17:12:17.439 31959 32003 D EhEngine: https://exhentai.org/
10-19 17:12:17.452 31959 32003 D TrafficStats: tagSocket(126) with statsTag=0xffffffff, statsUid=-1
10-19 17:12:17.756 31959 31959 D VRI[MainActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
10-19 17:12:17.757 31959 31959 V AutofillManager: requestHideFillUi(null): anchor = null
10-19 17:12:17.772 31959 31959 D VRI[MainActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
10-19 17:12:17.789 31959 31959 D VRI[MainActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
10-19 17:12:17.797 31959 31959 D VRI[MainActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
10-19 17:12:17.800 31959 31959 D VRI[MainActivity]: handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
10-19 17:12:21.026 31959 32003 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.tagName()' on a null object reference
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.parser.GalleryListParser.parse(GalleryListParser.java:198)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:274)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:152)
10-19 17:12:21.026 31959 32003 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
10-19 17:12:21.026 31959 32003 W System.err: com.hippo.ehviewer.client.exception.EhException: 
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:152)
10-19 17:12:21.026 31959 32003 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 17:12:21.026 31959 32003 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
10-19 17:12:21.026 31959 32003 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
10-19 17:12:21.027 31959 31959 W System.err: com.hippo.ehviewer.client.exception.EhException: 
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:152)
10-19 17:12:21.027 31959 31959 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
10-19 17:12:21.027 31959 31959 W System.err: com.hippo.ehviewer.client.exception.EhException: 
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.doThrowException(EhEngine.java:130)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.throwException(EhEngine.java:153)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getGalleryList(EhEngine.java:277)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:152)
10-19 17:12:21.027 31959 31959 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 17:12:21.027 31959 31959 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
10-19 17:12:21.027 31959 31959 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
10-19 17:12:22.299 31959 31959 D VRI[MainActivity]: onFocusEvent false
10-19 17:12:22.299 31959 31959 D VRI[MainActivity]: send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8422 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
```

**Comment by Gaojianli** [comment]
解决了，必须使用网页登录才行，app自带登陆不好使
