### ISSUE TITLE
使用 SpiderQueen.obtainSpiderQueen 会导致下载后 .ehviewer 文件不生成

### ISSUE THREAD

**Issue by UjuiUjuMandan** [xiaojieonly/Ehviewer_CN_SXJ#993]
@xiaojieonly @eithwa
2023年11月 33ae123 在 `bindViewSecond()` 中使用了一次 `SpiderQueen.obtainSpiderQueen()`，以便获取当前阅读页数，由于未知原因，使用它会导致下载画廊后不生成 `.ehviewer` 文件，从而导致 #931 的问题。

只有进入下载后的画廊阅读界面一次，`.ehviewer`文件才会出现。

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已改，下一版上

**Comment by UjuiUjuMandan** [comment]
@xiaojieonly 

现在进入任何画廊详情页会

```
FATAL EXCEPTION: main
Process: com.xjs.ehviewer.debug, PID: 19492
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
at com.hippo.ehviewer.EhApplication.getExecutorService(EhApplication.java:722)
at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.bindReadProgress(GalleryDetailScene.java:997)
at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.bindViewSecond(GalleryDetailScene.java:973)
at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.onGetGalleryDetailSuccess(GalleryDetailScene.java:1795)
at com.hippo.ehviewer.ui.scene.gallery.detail.GetGalleryDetailListener.onSuccess(GetGalleryDetailListener.java:48)
at com.hippo.ehviewer.ui.scene.gallery.detail.GetGalleryDetailListener.onSuccess(GetGalleryDetailListener.java:18)
at com.hippo.ehviewer.client.EhClient$Task.onPostExecute(EhClient.java:216)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8194)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
> @xiaojieonly
> 
> 现在进入任何画廊详情页会
> 
> ```
> FATAL EXCEPTION: main
> Process: com.xjs.ehviewer.debug, PID: 19492
>  java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> at com.hippo.ehviewer.EhApplication.getExecutorService(EhApplication.java:722)
> at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.bindReadProgress(GalleryDetailScene.java:997)
> at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.bindViewSecond(GalleryDetailScene.java:973)
> at com.hippo.ehviewer.ui.scene.gallery.detail.GalleryDetailScene.onGetGalleryDetailSuccess(GalleryDetailScene.java:1795)
> at com.hippo.ehviewer.ui.scene.gallery.detail.GetGalleryDetailListener.onSuccess(GetGalleryDetailListener.java:48)
> at com.hippo.ehviewer.ui.scene.gallery.detail.GetGalleryDetailListener.onSuccess(GetGalleryDetailListener.java:18)
> at com.hippo.ehviewer.client.EhClient$Task.onPostExecute(EhClient.java:216)
> at android.os.AsyncTask.finish(AsyncTask.java:771)
> at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
> at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loopOnce(Looper.java:205)
> at android.os.Looper.loop(Looper.java:294)
> at android.app.ActivityThread.main(ActivityThread.java:8194)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> ```

@UjuiUjuMandan 好了，你再看看

**Comment by xiaojieonly** [comment]
@UjuiUjuMandan 
有一说一，你主页的签名有点难以言表。。。。。

**Comment by UjuiUjuMandan** [comment]
@xiaojieonly 现在有另一个问题：比如我看到第4页，那么画廊详情页就显示页数`4/0P`，后面的值应该是总页数，而不是0。

**Comment by xiaojieonly** [comment]
我看看

**Comment by xiaojieonly** [comment]
好了 @UjuiUjuMandan

**Comment by UjuiUjuMandan** [comment]
没问题了。
